### ISSUE TITLE
Bug in the connection to the sim

### ISSUE THREAD

**Issue by zxyang7** [FredericoMetelo/TaskOffloadingAgentLibrary#6]
After I start the DebugEnv.py and  "java -jar target/peersim-srv-0.0.1-SNAPSHOT.jar",
something goes wrong:
In the IDE:
Traceback (most recent call last):
  File "/home/zxyang/PeersimGym/TaskOffloadingAgentLibrary/src/DebugEnv.py", line 206, in <module>
    env.reset()
  File "/home/zxyang/PeersimGym/peersim-environment/src/peersim-gym/peersim_gym/envs/PeersimEnv.py", line 240, in reset
    observations, done, info = self.__get_obs()
                               ^^^^^^^^^^^^^^^^
  File "/home/zxyang/PeersimGym/peersim-environment/src/peersim-gym/peersim_gym/envs/PeersimEnv.py", line 349, in __get_obs
    raise Exception("Failed to get observation after 100 tries, environment is down.")
Exception: Failed to get observation after 100 tries, environment is down.

In the terminal:
Getting state
2024-05-19T17:12:20.311+08:00 ERROR 43834 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.NullPointerException: Cannot load from object array because "PeersimSimulator.peersim.core.Network.node" is null] with root cause

java.lang.NullPointerException: Cannot load from object array because "PeersimSimulator.peersim.core.Network.node" is null
        at PeersimSimulator.peersim.core.Network.get(Network.java:217) ~[classes!/:0.0.1-SNAPSHOT]
        at PeersimSimulator.peersim.env.SimulationManagers.MdpApi.getState(MdpApi.java:46) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1080) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.0.4.jar!/:6.0.4]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.4.jar!/:6.0.4]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.5.jar!/:na]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

**Comment by zxyang7** [comment]
Looks like the Agent can't get the state from the simulation smoothly, but I have no idea why.

**Comment by FredericoMetelo** [comment]
Do you start the simulation manually and then the environment? The environment launches a thread with the simulation, so there is no need to launch it manually.

**Comment by FredericoMetelo** [comment]
I merged the dev branch with the master in the simulation environment. That took care of some problems. Try and update the environment. I'm still working on the documentation  for the features added. Will try to add it asap.
Quick and Dirty, I added the option to change the way the delay's are computed in communications between specific layers. See bellow an example config.

protocol.urt.channelTypes PeersimSimulator.peersim.env.Transport.OpticalFiberSNR;PeersimSimulator.peersim.env.Transport.WirelessSNR
protocol.urt.channelTypesBetweenLayers 0,0,1;0,0,1;1,1,1
protocol.urt.SNR 45
protocol.wrk.energyCostComm 10
protocol.wrk.energyCostComp 1

The way It works is that you can specify per layer pair what class to use to compute the maximum channel capacity. protocol.urt.channelTypes is the classes to load, this are arranged in an array. The protocol.urt.channelTypesBetweenLayers  is a matrix with the channel to consider per layer pair. The channel is represented by it's index in the array.

You can change this from the configuration dictionary you pass to the environment by setting the parameters:
```
ch.generate_config_dict(
...
channelTypes="PeersimSimulator.peersim.env.Transport.OpticalFiberSNR;PeersimSimulator.peersim.env.Transport.WirelessSNR",
channelTypesBetweenLayers="0,0,1;0,0,1;1,1,1",
...)
```
I still have not added a default behaviour, so you must always set the variables. I will be adding the default behaviour asap

**Comment by zxyang7** [comment]
> Do you start the simulation manually and then the environment? The environment launches a thread with the simulation, so there is no need to launch it manually.
Not exactly, I start the Env first and then the simulation, if I start the sim first, there will be another error tells me to release the 8080 port.
Actually, when I start the environment only (if you mean the DebugEnv.py), it will keep telling me "Attempting to connect the simulation", which seems like the simulation hasn't been started, that`s why I tried to launch the simulation in my terminal manually.
I will try your solution above, sincerely thanks for your reply.

**Comment by zxyang7** [comment]
<img width="589" alt="Screenshot 2024-05-21 190035" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/103874903/0db79f58-d384-46a9-bd6e-54001fb4564f">
As for the OS, well, it may be a little complex.
My OS is:
Windows 11, version 23H2 with **WSL2(Windows Subsystem for Linux) **
**Linux version 5.15.146.1-microsoft-standard-WSL2 (root@65c757a075e2) (gcc (GCC) 11.2.0, GNU ld (GNU Binutils) 2.37) #1 SMP Thu Jan 11 04:09:03 UTC 2024**
Released version:
**Ubuntu 22.04.1 LTS**
I followed the guide entirely from the readme of the simulation.
By the way, when I used Conda on win11 to install the necessary dependencies, there were some dependencies unavailable for Win11(but available for Linux, cause it's smoothly to install the dependencies in WSL), the list is in attached files.

**Comment by FredericoMetelo** [comment]
I actually never used WSL for the environment. I used a different set of dependencies,```Setup/requirements_win.yaml```.
But that is missing from the README, I'll add it right away. Thanks for helping me catch that.

It might take a while to finish setting up WSL though. I will try to do that today after work. In the meanwhile, if you have the availability I recommend trying the windows direct set up, I'll update the README on the Peersim-environment right away.

**Comment by FredericoMetelo** [comment]
Sorry, I couldn't set up windows with WSL yesterday. Did you manage to make it work with the windows setup?
You may need to change the paths to windows IE swap the "/" for "\".

**Comment by zxyang7** [comment]
Sorry for late reply. 
I tried to setting up on my Windows and ran, but still, it kept telling me "Attempting to connect to the environment".
<img width="950" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/103874903/26e3a31a-f51a-4ba4-9915-626a04d7b4df">

And I found this error in the src/logs/log_run_1.txt (By the way, I found this on WSL version, too, entirely same content, 
also generated by the DebugEnv.py):
Error: LinkageError occurred while loading main class org.springframework.boot.loader.JarLauncher
	java.lang.UnsupportedClassVersionError: org/springframework/boot/loader/JarLauncher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

But I am pretty sure that my java version can't be lower than 17.0.5:
<img width="570" alt="image" src="https://github.com/FredericoMetelo/TaskOffloadingAgentLibrary/assets/103874903/77219bd1-a6cd-4c10-a156-f3e9be430b23">
Now I am trying to search and delete every java version on my computer and reset the java.
Also, I am trying to reset up all these on a new computer of my roommate which is without any java version.

**Comment by FredericoMetelo** [comment]
I am using Java 19.0.2 (OpenJDK version) to compile and run the simulation. At least the problem has shifted to a versioning problem. I'll see if there is a way to package the environment in such a way that it's not required to change the PC's java version. Otherwise, I'll change the simulation to specify the path to the java executable, that way multiple java versions may be installed at the same time. 

If it might interest you, personally, I use [SDKMAN](https://sdkman.io/) to manage what version of Java is installed.

**Comment by FredericoMetelo** [comment]
Thank you for your patience. I'm fairly new to managing repositories and making programs that are compatible across different setups. Your, help and patience have been a great boon.

**Comment by zxyang7** [comment]
That's OK. You are the first one that I've seen to develop and publish an environment for the MADRL Task offloading of edge computing. That's genius, bro. After I finished setting this up, I will recommend it to all my colleague in the lab.

**Comment by FredericoMetelo** [comment]
1. Did changing to Java 19 fix the issues for you @zxyang7 ? If so, I will close the issue. And thanks for the positivity, I thought I had already thanked you earlier but for some reason didn't send the message, mb. It truly is appreciated

**Comment by zxyang7** [comment]
Oh, finally I managed to set up the environment on Java 17.0.11 on my roommate's computer, it seems that old version java still hiding in my own computer.
Thanks for your help and sorry for wasting your time, I guess I still have a lot to learn.

**Comment by FredericoMetelo** [comment]
Don't worry about that. I'll help however I can.
